sudo php warcurl.php haaa > /dev/null&
sudo php warcurl.php ha.aa > /dev/null&
sudo php warcurl.php ha.ab > /dev/null&
sudo php warcurl.php ha.ac > /dev/null&
sudo php warcurl.php ha.ad > /dev/null&
sudo php warcurl.php ha.ae > /dev/null&
sudo php warcurl.php ha.af > /dev/null&
sudo php warcurl.php ha.ag > /dev/null&
sudo php warcurl.php ha.ah > /dev/null&
sudo php warcurl.php ha.ai > /dev/null&
