sudo php warcurl.php waaa > /dev/null&
sudo php warcurl.php waab > /dev/null&
sudo php warcurl.php waac > /dev/null&
sudo php warcurl.php waad > /dev/null&
sudo php warcurl.php waae > /dev/null&
sudo php warcurl.php waaf > /dev/null&
sudo php warcurl.php waag > /dev/null&
sudo php warcurl.php waah > /dev/null&
sudo php warcurl.php waai > /dev/null&
sudo php warcurl.php waaj > /dev/null&
sudo php warcurl.php waak > /dev/null&
sudo php warcurl.php waal > /dev/null&
sudo php warcurl.php waam > /dev/null&
sudo php warcurl.php waao > /dev/null&
sudo php warcurl.php waap > /dev/null&
sudo php warcurl.php waaq > /dev/null&
sudo php warcurl.php waar > /dev/null&
sudo php warcurl.php waas > /dev/null&
sudo php warcurl.php waat > /dev/null&
sudo php warcurl.php waau > /dev/null&
sudo php warcurl.php waav > /dev/null&
sudo php warcurl.php waaw > /dev/null&
sudo php warcurl.php waax > /dev/null&
sudo php warcurl.php waay > /dev/null&
sudo php warcurl.php waaz > /dev/null&
